### ISSUE TITLE
Eslint shouldn't be disabled

### ISSUE THREAD

**Issue by chuenlum** [thejuniordevops/cl#12]
We use eslint to help us improve code quality. Many of the rules highlight areas where there could be potential bugs / areas we can improve on. Most of the time, we shouldn't disable these rules.

To remove comments that disable eslint. To handle errors / warnings from eslint by referring to eslint documentation and solving them the right way.

Examples:

- https://github.com/thejuniordevops/cl/blob/master/app/App.js#L1-L3
- other files as needed

**Comment by thejuniordevops** [comment]
Done
