### ISSUE TITLE
Have short concise data representation

### ISSUE THREAD

**Issue by chuenlum** [thejuniordevops/cl#14]
Data that should be grouped together is stored in state separately using multiple variables, e.g. emptySun, emptyMon. This makes code unnecessary long and more difficult to manage.

To change the way data is represented so we don't need to repeat similar things unnecessarily.

- https://github.com/thejuniordevops/cl/blob/master/app/App.js#L33-L39
- https://github.com/thejuniordevops/cl/blob/master/app/App.js#L126-L132

**Comment by chuenlum** [comment]
Related: https://github.com/thejuniordevops/cl/blob/master/app/Components/Days/index.js#L36-L42

**Comment by edidevs** [comment]
Done
