### ISSUE TITLE
Remove all callbacks that make code complicated

### ISSUE THREAD

**Issue by chuenlum** [thejuniordevops/cl#15]
Using callbacks can make code more difficult to follow. It's ok to have more imperative / procedural code

E.g. 

- https://github.com/thejuniordevops/cl/blob/master/app/utils/checkEmpty.js is just returning an array. We don't need to create a function for that and use it in a callback https://github.com/thejuniordevops/cl/blob/master/app/App.js#L106. We can just have it as an array
- https://github.com/thejuniordevops/cl/blob/master/app/App.js#L67-L72 and https://github.com/thejuniordevops/cl/blob/master/app/App.js#L102-L104 are just unnecessary callbacks
- others...

**Comment by thejuniordevops** [comment]
Done
