### ISSUE TITLE
Separate styles into different file

### ISSUE THREAD

**Issue by chuenlum** [thejuniordevops/cl#16]
https://github.com/thejuniordevops/cl/blob/master/app/App.js#L155-L227 can be refactored to separate file. Same for other files e.g. https://github.com/thejuniordevops/cl/blob/master/app/Components/Days/index.js and others

Reference https://github.com/thecodingmachine/react-native-boilerplate/tree/master/App/Containers/SplashScreen

**Comment by thejuniordevops** [comment]
done
