### ISSUE TITLE
Code is not DRY in places with `switch` statements

### ISSUE THREAD

**Issue by chuenlum** [thejuniordevops/cl#2]
Sections of the code with `switch` have much repeated code. That is not DRY. Hence, changing the code requires more effort to make sure that there's no human error. Please refactor and make the code more DRY.

- https://github.com/thejuniordevops/cl/blob/master/App.js#L79-L125
- https://github.com/thejuniordevops/cl/blob/master/App.js#L183-L310
- https://github.com/thejuniordevops/cl/blob/master/App.js#L419-L445

**Comment by thejuniordevops** [comment]
Done, all repeated code are made into a single function

**Comment by chuenlum** [comment]
There's still quite a lot of repeated code within the `switch` statements. e.g. 

```
        case '1':
          this.pushDeal(item, sun);
          break;
        case '2':
          this.pushDeal(item, mon);
          break;
```

This kind of code is repeated multiple times with small variation.

```
      case 1:
        if (this.state.sun.length > 0) {
          this.getEachDeal(this.state.sun, index);
        } else {
          this.selectDeals(value + 1, index);
        }

        break;
      case 2:
        if (this.state.mon.length > 0) {
          this.getEachDeal(this.state.mon, index);
        } else {
          this.selectDeals(value + 1, index);
        }

        break;
```

This code is also repeated, but with small variation.

```
                            case '1':
                              this.selectDeals(1, index);
                              break;
                            case '2':
                              this.selectDeals(2, index);
                              break;
```

This is also repeated multiple times with small variation.

Please refactor so that it's much cleaner.

Example for https://github.com/thejuniordevops/cl/blob/1f27efe9a3322194a3daea7d0e8a6f0475c55510/app/App.js#L293-L318:

```
                        onPress={() => {
                          this.selectDeals(parseInt(dayOfTheWeek), index)
                        }}
```

**Comment by chuenlum** [comment]
Perhaps changing the data representation will help? Instead of having `mon`, `tue` ... `sun` in state, could use just 1 variable? Other solutions welcomed.

```
this.state = {
  ...
  daysOfWeek: {
    '0': [],
    '1': [],
    '2': [],
    '3': [],
    ...
  },
  ...
};
```

https://stackoverflow.com/questions/3633362/is-there-any-way-to-use-a-numeric-type-as-an-object-key

**Comment by thejuniordevops** [comment]
Done, the code have been refactored in place of switch statement

**Comment by thejuniordevops** [comment]
Done
