### ISSUE TITLE
Not following formatting standard per .prettierrc.js, makes code difficult to read

### ISSUE THREAD

**Issue by chuenlum** [thejuniordevops/cl#3]
There's no formatting standard implemented. Hence the following issues were spotted.

The current repo has a https://github.com/thejuniordevops/cl/blob/master/.prettierrc.js. Hence please use Prettier package to format the code. e.g. for VS Code this can help -> https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode

- Same level of indentation makes the hierarchy of components difficult to understand

![image](https://user-images.githubusercontent.com/12426535/71301353-fcd5ce80-23d8-11ea-8d6b-4e207c7af42d.png)

- Too many inline styles make code difficult to read. Best is to refactor inline styles out.

![image](https://user-images.githubusercontent.com/12426535/71301339-ea5b9500-23d8-11ea-8ee1-6fe4e6e8a62b.png)

**Comment by thejuniordevops** [comment]
Done, all code are more readable now
