### ISSUE TITLE
Use named variables to explain code

### ISSUE THREAD

**Issue by chuenlum** [thejuniordevops/cl#4]
Variables without good naming makes it more difficult to understand code.

- This is still ok because `reduce` (and `pad` function later in the code) is still easy to understand https://github.com/thejuniordevops/cl/blob/master/App.js#L157-L159
- Using `item[3]` here is more confusing unless we look in another part of the code and realise that it's actually the day of week. To refactor e.g. using `const dayOfWeek = item[3]; switch (dayOfWeek) ...`  https://github.com/thejuniordevops/cl/blob/master/App.js#L419

**Comment by thejuniordevops** [comment]
change item[3] to dayOfTheWeek

**Comment by chuenlum** [comment]
`item[0]` can be better explained using named variable too https://github.com/thejuniordevops/cl/blob/a42a4a701f75bbf6a5c268837e3bcdb1d51bb796/app/App.js#L300
