### ISSUE TITLE
New requirement: code organisation into different files

### ISSUE THREAD

**Issue by chuenlum** [thejuniordevops/cl#6]
As the main developer for a project, it's best to set good examples to other developers in the same team for them to follow.

Some of the code can be refactored into other files to make code organisation neater. Some examples:

- Multiple occurrences of `#FB4D64` color. 
- Helper functions like `pad` can be refactored into a `helpers` or `utils` folder https://github.com/thejuniordevops/cl/blob/d9cbdcd358749ed78989d69eb231dcaf856f1a17/App.js#L388
- Date manipulation functions can be refactored into some domain specific business logic file
- etc

In our project, we use https://github.com/thecodingmachine/react-native-boilerplate, which offers some directory structure, including `Theme` files for style constants https://github.com/thecodingmachine/react-native-boilerplate/tree/master/App/Theme

**Comment by thejuniordevops** [comment]
Done, the codes are now organized into separate folders

**Comment by chuenlum** [comment]
Please also refactor code so that `deals` is a separate component in `app/Components/Deals` folder

https://github.com/thejuniordevops/cl/blob/a42a4a701f75bbf6a5c268837e3bcdb1d51bb796/app/App.js#L211-L281

**Comment by chuenlum** [comment]
Please refactor **most** functions like `showData`, `checkEmpty`, `findMaxDiscount`, `findIndexOfMaxDisount`, `getEachDeal`,  to a different file(s). After moving to a different file, this will force the functions to accept parameters instead of using `this.state` in the functions. This makes it more testable using Jest automated code. We will be doing the same in our project.

Ideally, after doing these refactoring, we can have `App.js` just:

1. query the endpoint,
2. pass data to other functions that manipulate the data, and
3. render

In general, please note that we will do similar code management techniques in our project so that business logic is organised separately, making the functions more testable using Jest.

**Comment by thejuniordevops** [comment]
Done, the code has been reorganized to make it cleaner

**Comment by thejuniordevops** [comment]
Done, the code has been reorganized to make it cleaner
