### ISSUE TITLE
Multiple discounts selected when date changed

### ISSUE THREAD

**Issue by chuenlum** [thejuniordevops/cl#7]
# Steps to replicate

1. Select any day where there's > 1 timeslot with the highest discount, e.g. 24 December

# Expect

Only the earlier timeslot should be selected

# Actual

All timeslots that have the highest discount are selected

![Simulator Screen Shot - iPhone 11 - 2019-12-21 at 22 22 02](https://user-images.githubusercontent.com/12426535/71309224-6dfc9c80-2440-11ea-8180-2e87d3b5da70.png)

**Comment by thejuniordevops** [comment]
Done, only the first highest discount selected now.
