### ISSUE TITLE
Inaccurate timeslots

### ISSUE THREAD

**Issue by chuenlum** [thejuniordevops/cl#8]
The data has no active timeslots for Saturday and Sunday. However, when we check the state of the app, we see that the state of Friday and Saturday are empty arrays instead.

![image](https://user-images.githubusercontent.com/12426535/71309657-95099d00-2445-11ea-91c8-0d7596fbdcdb.png)

**Comment by chuenlum** [comment]
Moreover, even though the states for Friday and Saturday are empty arrays, there are timeslots displayed. This is weird

**Comment by thejuniordevops** [comment]
Sorry, silly mistake, I miss the information, it was designed to show up the data in the next day even there is no data, now the issue has been fixed, if there is no data for the day selected, then the day won't show up. Done
