### ISSUE TITLE
Saturday and Sunday should not appear as there are no active timeslots

### ISSUE THREAD

**Issue by chuenlum** [thejuniordevops/cl#9]
The data doesn't have any active timeslots for Saturday and Sunday. Hence per the requirements, there should not be any dates for Saturdays and Sundays.

However, we see dates like 21 Dec, 22 Dec, 28 Dec, 29 Dec, 04 Jan, which are all Sat / Sun. These should not be there.

![image](https://user-images.githubusercontent.com/12426535/71309687-ca15ef80-2445-11ea-9d89-ed1c8f8e9759.png)

**Comment by thejuniordevops** [comment]
The date in which there is no data won't show up anymore. Done

**Comment by chuenlum** [comment]
This is still inaccurate. Please check

**Comment by thejuniordevops** [comment]
Done,

**Comment by thejuniordevops** [comment]
Done
